### ISSUE TITLE
Make the sidebar menu either scrollable or static

### ISSUE THREAD

**Issue by Smokyish** [trustlines-protocol/tl-docs#1]
Currently the sidebar scrolls and moves together with the inner element page. It should be scrollable in itself or be static so it doesn't move when moving down on the page.

**Comment by LalitNM** [comment]
I would like to work on this.

**Comment by Smokyish** [comment]
@LalitNM Please do, Pull Requests are always welcome!

**Comment by LalitNM** [comment]
I think this problem is only on large screens, and we can fix it by displaying the sidebar collapsible-button all the time, just like on small and medium screens.
What do you say @Smokyish ?

**Comment by Smokyish** [comment]
Yes, it's a lesser issue on smaller screens, but might also run to the same issue as the number of menu items increases and the height of the sidebar grows. So the collapsible button would be one solution and somewhat of a quick fix, but it might not be a long-term solution 🤔 

What we also could consider in addition would be a "back to top" button placed i.e., on the bottom right corner of the screen.

**Comment by LalitNM** [comment]
I am a little bit confused. What is your issue exactly? Can you re-frame your issue. You can also open a new issue for back-to-top button.

**Comment by Smokyish** [comment]
![image](https://user-images.githubusercontent.com/21331903/80947935-d483c500-8df9-11ea-891f-353f675f1983.png)

@LalitNM If the menu is long, ie. has lots of items or many of the submenus are opened, the sidebar menu becomes larger than can fit on the screen. Now if you have scrolled down on a page, the menu isn't scrollable so that you could only scroll up on the menu to ie. see the Home item or anything that gets cut off, you need to scroll up to the top of the page in order to see the menu items that have been cut off. This isn't optimal since as the sidebar gets bigger, it gets more tedious to scroll back up to the top to see the menu items that you might want to move to.

**Comment by Smokyish** [comment]
Closed by https://github.com/trustlines-protocol/tl-docs/pull/2
